# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmbSwZVVOMEsjFM3jpuif-cwJFhJbbIk
"""

from google.colab import files
import pandas as pd
uploaded = files.upload()
df = pd.read_csv("churn.csv")
print(df)

print(df.head())

df.info()

df.describe(include='all')

df.shape

df.isnull().sum()

print(df.columns)

df = df.drop(['RowNumber','CustomerId','Surname'], axis=1)
print(df.head())

df['Gender'] = df['Gender'].map({'Male':1,'Female':0})



print(df.head())

print(df.columns)

df = pd.get_dummies(df, columns=['Geography'], drop_first=True)
print(df.head())

print(df['Exited'].value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Exited', data=df)

plt.title("Customer Churn Distribution")
plt.xlabel("Churn (0 = Stay, 1 = Left)")
plt.ylabel("Number of Customers")

plt.show()

sns.boxplot(x='Exited', y='Age', data=df)

plt.title("Age Distribution by Customer Churn")
plt.xlabel("Churn (0 = Stay, 1 = Left)")
plt.ylabel("Age")

plt.show()

sns.boxplot(x='Exited', y='Balance', data=df)

plt.title("Balance Distribution by Customer Churn")
plt.xlabel("Churn (0 = Stay, 1 = Left)")
plt.ylabel("Account Balance")

plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

print(df.corr()['Exited'].sort_values(ascending=False))

X = df.drop('Exited', axis=1)
y = df['Exited']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)

model.fit(X_train, y_train)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(cm, annot=True, fmt='d')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

import numpy as np
new_customer = np.array([[600, 40, 3, 60000, 2, 1, 1, 50000, 1, 1, 0]])
prediction = model.predict(new_customer)
print("Chances of Leaving:" if prediction[0] == 1 else "Will Stay in Bank")

import pandas as pd

features = X.columns
# Logistic Regression ke liye coefficients use hote hain
importances = model.coef_[0]
importance_df = pd.DataFrame({'Feature': features, 'Importance': abs(importances)}).sort_values(by='Importance', ascending=False)

print(importance_df)

import matplotlib.pyplot as plt

importance_df.plot(kind='bar', x='Feature', y='Importance', color='teal')
plt.title('Bank Churn Factors (Top to Bottom)')
plt.ylabel('Importance Score')
plt.show()